name: CI
on: [push, pull_request]
jobs:
  test:
    name: go${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.12', '1.14', '1.16', '1.18', '1.20', '1.21']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: go test -v -race ./...
